import subprocess
import urllib.request
import urllib.parse
import json
from dotenv import load_dotenv
from google.adk.agents.llm_agent import Agent
from google.adk.models.lite_llm import LiteLlm
from google.adk.tools.exit_loop_tool import exit_loop

load_dotenv()

def shutdown_orin_nano():
    """Shuts down the remote Orin Nano system."""
    subprocess.run(["ssh", "orinnano", "sudo", "shutdown", "-h", "now"])
    return "Shutdown command sent to Orin Nano."

def create_file(file_path: str, content: str):
    """Creates a file with a paragraph generated by model which will be detailed in prompt"""
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    return f"File '{file_path}' created successfully."

def get_tomorrow_weather_forecast(place: str):
    """Provides the tomorrow weather forecast for a given place."""
    try:
        url = f"https://wttr.in/{urllib.parse.quote(place)}?format=j1"
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req) as response:
            data = json.loads(response.read().decode('utf-8'))
            tomorrow = data['weather'][1]
            condition = tomorrow['hourly'][4]['weatherDesc'][0]['value']
            return f"Tomorrow's forecast for {place}: Max {tomorrow['maxtempC']}°C, Min {tomorrow['mintempC']}°C. Conditions: {condition}."
    except Exception as e:
        return f"Could not fetch weather forecast for {place}: {e}"

def query_pdf_book(pdf_path: str, query: str):
    """Reads a hundreds page of pdf and answers the queries based only on the book."""
    try:
        from pypdf import PdfReader
        from litellm import completion
        reader = PdfReader(pdf_path)
        
        keywords = [kw.lower() for kw in query.split() if len(kw) > 3]
        if not keywords:
            keywords = [kw.lower() for kw in query.split()]
            
        scored_pages = []
        for i, page in enumerate(reader.pages):
            text = page.extract_text()
            if text:
                score = sum(text.lower().count(kw) for kw in keywords)
                scored_pages.append((score, i, text))
                
        scored_pages.sort(key=lambda x: x[0], reverse=True)
        top_pages = scored_pages[:5] # Take top 5 relevant pages
        
        context = "\n".join([f"--- Page {p[1]+1} ---\n{p[2]}" for p in top_pages])
        prompt = f"Answer the query based ONLY on the following book excerpts:\n\n{context}\n\nQuery: {query}\nAnswer:"
        
        response = completion(model="ollama_chat/qwen3:4b", messages=[{"role": "user", "content": prompt}])
        return response.choices[0].message.content
    except Exception as e:
        return f"Error querying PDF: {e}"

def get_home_appliances_door_status():
    """Gets the door status (Open/Closed) of connected Siemens home appliances (like Dishwasher or FridgeFreezer) using the Home Connect API."""
    import subprocess
    import sys
    import os
    try:
        # Run the script using the current python executable (from the venv)
        script_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "siemens-home-connect-tool.py")
        result = subprocess.run([sys.executable, script_path], capture_output=True, text=True)
        if result.returncode == 0:
            return result.stdout.strip()
        else:
            return f"Error executing tool: {result.stderr.strip() or result.stdout.strip()}"
    except Exception as e:
        return f"Exception while fetching appliance status: {e}"

root_agent = Agent(
    model=LiteLlm(model='ollama_chat/qwen3:4b'),
    name='root_agent',
    description='A helpful assistant for user questions.',
    instruction="""Answer user questions to the best of your knowledge.
If the user asks you to shutdown the Orin Nano, use the shutdown_orin_nano tool.
If the user asks you to shutdown the system run or yourself, use the exit_loop tool.
If the user asks you to create a file, use the create_file tool.
If the user asks you for tomorrow's weather forecast for a given place, use the get_tomorrow_weather_forecast tool.
If the user asks you to get a hundreds page of pdf and answer queries based only on the book, use the query_pdf_book tool.
If the user asks about the door status of connected Siemens home appliances (like the Fridge or Dishwasher), use the get_home_appliances_door_status tool.""",
    tools=[exit_loop, shutdown_orin_nano, create_file, get_tomorrow_weather_forecast, query_pdf_book, get_home_appliances_door_status],
)
